if(NOT DEFINED CATALOG OR NOT EXISTS "${CATALOG}")
    message(FATAL_ERROR "EpochEngineExtensions catalog file is missing")
endif()

file(READ "${CATALOG}" catalog_json)
string(JSON schema GET "${catalog_json}" schema)
string(JSON repository GET "${catalog_json}" repository)
string(JSON availability GET "${catalog_json}" availability)
string(JSON automatic_execution GET "${catalog_json}" automatic_execution)
string(JSON entry_count LENGTH "${catalog_json}" entries)

if(NOT schema STREQUAL "epoch-engine-extension-catalog/v1")
    message(FATAL_ERROR "Unexpected Extensions catalog schema: ${schema}")
endif()
if(NOT repository STREQUAL "EpochEngineExtensions")
    message(FATAL_ERROR "Unexpected Extensions repository identity: ${repository}")
endif()
if(NOT availability STREQUAL "descriptor_only")
    message(FATAL_ERROR "Extensions catalog must remain descriptor-only")
endif()
if(automatic_execution)
    message(FATAL_ERROR "Extensions catalog must not request automatic execution")
endif()
if(NOT entry_count EQUAL 8)
    message(FATAL_ERROR "Expected 8 extension descriptors, found ${entry_count}")
endif()

set(package_ids)
math(EXPR last_index "${entry_count} - 1")
foreach(index RANGE 0 ${last_index})
    string(JSON stable_id GET "${catalog_json}" entries ${index} stable_id)
    string(JSON package_id GET "${catalog_json}" entries ${index} package_id)
    string(JSON entry_availability GET "${catalog_json}" entries ${index} availability)
    string(JSON installable GET "${catalog_json}" entries ${index} installable_payload)
    string(JSON entry_auto GET "${catalog_json}" entries ${index} automatic_execution)
    string(LENGTH "${stable_id}" stable_id_length)
    if(NOT stable_id_length EQUAL 16 OR NOT stable_id MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Entry ${index} has an invalid stable ID")
    endif()
    if(package_id IN_LIST package_ids)
        message(FATAL_ERROR "Duplicate package ID: ${package_id}")
    endif()
    list(APPEND package_ids "${package_id}")
    if(NOT entry_availability STREQUAL "descriptor_only" OR installable OR entry_auto)
        message(FATAL_ERROR "Entry ${package_id} claims an unavailable payload or automatic execution")
    endif()
endforeach()
