if(NOT DEFINED CATALOG OR NOT EXISTS "${CATALOG}")
    message(FATAL_ERROR "EpochEngineExtensions catalog file is missing")
endif()

file(READ "${CATALOG}" catalog_json)
string(JSON schema GET "${catalog_json}" schema)
string(JSON repository GET "${catalog_json}" repository)
string(JSON availability GET "${catalog_json}" availability)
string(JSON automatic_execution GET "${catalog_json}" automatic_execution)
string(JSON entry_count LENGTH "${catalog_json}" entries)

if(NOT schema STREQUAL "epoch-engine-extension-catalog/v1")
    message(FATAL_ERROR "Unexpected Extensions catalog schema: ${schema}")
endif()
if(NOT repository STREQUAL "EpochEngineExtensions")
    message(FATAL_ERROR "Unexpected Extensions repository identity: ${repository}")
endif()
if(NOT availability STREQUAL "mixed_local_source")
    message(FATAL_ERROR "Extensions catalog must expose the bounded mixed local-source state")
endif()
if(automatic_execution)
    message(FATAL_ERROR "Extensions catalog must not request automatic execution")
endif()
if(NOT entry_count EQUAL 8)
    message(FATAL_ERROR "Expected 8 extension descriptors, found ${entry_count}")
endif()

set(package_ids)
set(source_package_count 0)
math(EXPR last_index "${entry_count} - 1")
foreach(index RANGE 0 ${last_index})
    string(JSON stable_id GET "${catalog_json}" entries ${index} stable_id)
    string(JSON package_id GET "${catalog_json}" entries ${index} package_id)
    string(JSON entry_availability GET "${catalog_json}" entries ${index} availability)
    string(JSON installable GET "${catalog_json}" entries ${index} installable_payload)
    string(JSON entry_auto GET "${catalog_json}" entries ${index} automatic_execution)
    string(LENGTH "${stable_id}" stable_id_length)
    if(NOT stable_id_length EQUAL 16 OR NOT stable_id MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Entry ${index} has an invalid stable ID")
    endif()
    if(package_id IN_LIST package_ids)
        message(FATAL_ERROR "Duplicate package ID: ${package_id}")
    endif()
    list(APPEND package_ids "${package_id}")
    if(entry_auto)
        message(FATAL_ERROR "Entry ${package_id} requests automatic execution")
    endif()

    if(package_id STREQUAL "demo_tiered_terrain")
        if(NOT entry_availability STREQUAL "source_available_local" OR NOT installable)
            message(FATAL_ERROR "Tiered terrain must be the admitted local source package")
        endif()
        string(JSON source_key GET "${catalog_json}" entries ${index} source_key)
        if(NOT source_key STREQUAL "demonstrations/tiered_terrain")
            message(FATAL_ERROR "Tiered terrain source key is not canonical")
        endif()
        get_filename_component(catalog_directory "${CATALOG}" DIRECTORY)
        get_filename_component(repository_root "${catalog_directory}" DIRECTORY)
        foreach(required_source IN ITEMS
            LICENSE
            README.md
            modules/tiered_terrain.generator.ixx
            tests/tiered_terrain.generator_contract.cpp
        )
            if(NOT EXISTS "${repository_root}/${source_key}/${required_source}")
                message(FATAL_ERROR "Tiered terrain source is incomplete: ${required_source}")
            endif()
        endforeach()
        math(EXPR source_package_count "${source_package_count} + 1")
    elseif(NOT entry_availability STREQUAL "descriptor_only" OR installable)
        message(FATAL_ERROR "Entry ${package_id} claims a payload without admitted source")
    endif()
endforeach()

if(NOT source_package_count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one local source package")
endif()

string(FIND "${catalog_json}" "https://" site_url_index)
if(NOT site_url_index EQUAL -1)
    message(FATAL_ERROR "Local source catalog must not claim a published download URL")
endif()
