# Build the ordinary portable configurations from an existing multi-config tree.
cmake_minimum_required(VERSION 4.4)
if(NOT DEFINED BINARY_DIR OR NOT EXISTS "${BINARY_DIR}/CMakeCache.txt")
    message(FATAL_ERROR "Pass -DBINARY_DIR=<configured multi-config CMake tree>.")
endif()
file(STRINGS "${BINARY_DIR}/CMakeCache.txt" _configuration_line
    REGEX "^CMAKE_CONFIGURATION_TYPES:[^=]*=")
if(NOT _configuration_line)
    message(FATAL_ERROR "Debug+Release batch builds require a multi-config tree; configure Ninja Multi-Config or Visual Studio first.")
endif()
string(REGEX REPLACE "^[^=]*=" "" _available "${_configuration_line}")
string(REPLACE "\\;" ";" _available "${_available}")
foreach(_configuration IN ITEMS Debug Release)
    if(NOT _configuration IN_LIST _available)
        message(FATAL_ERROR "Configured tree does not offer ${_configuration}.")
    endif()
endforeach()
foreach(_configuration IN ITEMS Debug Release)
    message(STATUS "Building ${_configuration} in ${BINARY_DIR}")
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config "${_configuration}"
        RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "${_configuration} build failed (${_result}); no subsequent build started.")
    endif()
endforeach()
