name: MSBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: Engine.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        shell: powershell
        run: nuget restore $env:SOLUTION_FILE_PATH

      - name: Build ConsoleApplication1
        shell: powershell
        run: >
          msbuild $env:SOLUTION_FILE_PATH
          /t:ConsoleApplication1
          /m:1
          /p:Configuration=$env:BUILD_CONFIGURATION
          /p:Platform=$env:BUILD_PLATFORM
          /clp:ErrorsOnly
